version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app/
      - web:/app/web
    environment:
      - ENTR_INOTIFY_WORKAROUND=TRUE
      - cors_list=http://localhost:3000
    env_file:
      - .env
    command: ['/app/cmd/api/hotReload.sh']
    ports:
      - '8080:8080'
  web:
    build:
      context: ./web/
    volumes:
      - ./web:/app/
      - nodemodules:/app/node_modules
    ports:
      - '3000:3000'
    command: ['pnpm', 'run', 'dev']
  golanglinter:
    profiles: ["lint"]
    image: golangci/golangci-lint:v1.46.2
    volumes:
      - .:/app
      - web:/app/web
    working_dir: /app
    command: ['./lint.sh']
volumes:
  nodemodules: {} # Ignore local node modules
  web: {} # Ignore web