version: "3.8"
services:
  api:
    build:
      context: .
    privileged: true
    volumes:
      - .:/app/
    environment:
      - ENTR_INOTIFY_WORKAROUND=TRUE
    env_file:
      - .env
    command: ['/app/cmd/api/hotReload.sh']
    ports:
      - '8080:8080'