apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digitaldexterityapi-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-api"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/cors-allow-methods: "POST, GET, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Origin, Content-Type, Accept, Authorization"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  tls:
  - hosts:
    - api.digitaldexterity.techytechster.com
    secretName: digitaldexterity-tls
  rules:
  - host: api.digitaldexterity.techytechster.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: digitaldexapi-service
            port:
              number: 8080