name: New Release Deployment
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  # deploy-api:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Setup Golang
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.18
  #     - name: Install oci-cli
  #       uses: bytesbay/oci-cli-action@v1.0.2
  #       with:
  #         user: "${{ secrets.OCI_USER }}"
  #         fingerprint: "${{ secrets.OCI_FINGERPRINT }}"
  #         tenancy: "${{ secrets.OCI_TENANCY }}"
  #         region: "${{ secrets.OCI_REGION }}"
  #         api_key: ${{ secrets.OCI_API_KEY }}
  #         verbose: true
  #     - name: Create KubeConfig
  #       run: echo "$KUBEBASE64" | base64 --decode > config
  #       env:
  #         KUBEBASE64: ${{ secrets.KUBEBASE64 }}
  #     - name: Check If created
  #       run: pwd
  #     - name: Deploy Kubernetes
  #       uses: pulumi/actions@v3
  #       with:
  #         command: up
  #         stack-name: digitaldexterity
  #         work-dir: cmd/infrastructure
  #       env:
  #         KUBECONFIG: /home/runner/work/Digital_Dexterity/Digital_Dexterity/config
  #         app_name: ${{ secrets.APP_NAME }}
  #         cors_list: ${{ secrets.CORS_LIST }}
  #         db_address: ${{ secrets.DB_ADDRESS }}
  #         db_password: ${{ secrets.DB_PASSWORD }}
  #         db_username: ${{ secrets.DB_USERNAME }}
  #         gh_token: ${{ secrets.GH_TOKEN }}
  #         gh_username: ${{ secrets.GH_USERNAME }}
  #         image: ${{ secrets.IMAGE }}
  #         secrets_store: ${{ secrets.SECRETS_STORE }}
  #         secret_key: ${{ secrets.secret_key }}
  #         PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: DEBUG
        run: ls
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
      - name: "Install Dependencies"
        run: pnpm install
      - name: "Build Web"
        run: pnpm build
      - name: "Deploy Web"
        run: pnpm deploy