name: status check
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lintapi:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  lintwebconsumer:
    name: Lint Web Consumer
    defaults:
      run:
        working-directory: web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml
      - name: "Install Modules"
        run: pnpm install
      - name: "Lint"
        run: pnpm lint